version: '3.8'
services:
  sql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: ji8lae0aequai!hee3In
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure-programming-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myUsername
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
    networks:
      - secure-programming-network

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - secure-programming-network

networks:
  secure-programming-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data: