version: '3'

services:
  backend:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - spring-postgres

  postgresql:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

networks:
  spring-postgres: